version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./www:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - shared

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8.3
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    depends_on:
      - redis
    networks:
      - shared
  
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - shared

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - shared

  adminer:
    image: adminer
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:8081
    links:
      - db

networks:
  shared:
    driver: bridge